# name: private-isu
services:
  nginx:
    image: nginx:1.24.0-alpine3.17-slim
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/public
      - ./nginx-logs:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - my_network

  app:
    # Go実装の場合は golang/ PHP実装の場合は php/
    build: golang/
    environment:
      ISUCONP_DB_HOST: mysql
      ISUCONP_DB_PORT: 3306
      ISUCONP_DB_USER: root
      ISUCONP_DB_PASSWORD: root
      ISUCONP_DB_NAME: isuconp
      ISUCONP_MEMCACHED_ADDRESS: memcached:11211
    networks:
      - my_network
    volumes:
      - ./public:/home/public
    init: true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g

  mysql:
    image: mysql:8.0
    environment:
      #- "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql:/var/lib/mysql
      - ./etc/my.cnf:/etc/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql-logs:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g

  memcached:
    image: memcached:1.6.22-alpine3.19
    networks:
        - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8081:80
    networks:
        - my_network

volumes:
  mysql:

networks:
  my_network:
